# 21-sftp.sh — SFTP frontend (sftp-ftp-2026-09 tree / GH issue #2):
#   21a. round-trip via the system sftp CLI with KEY auth (ssh-keygen
#        keypair generated in-case): put, ls, get + byte-compare, rm.
#   21b. host key auto-generated by the server into its workdir
#        (hostKeyFile option) and reused.
#   21c. negatives: wrong key and wrong password fail cleanly and the
#        server stays up.
#
# Private-server pattern (cases 14–20): the suite server is left untouched.
set -u
E21_ROOT=$(mktemp -d /tmp/e2e21-sftp.XXXXXX)
E21_WORK=$(mktemp -d /tmp/e2e21-work.XXXXXX)
E21_CERT=$(mktemp -d /tmp/e2e21-cert.XXXXXX)
E21_BKT='e2e21-sftp-bkt'
E21_PORT=$(python3 - <<'PY'
import socket
s = socket.socket()
s.bind(("127.0.0.1", 0))
print(s.getsockname()[1])
s.close()
PY
)
openssl req -x509 -newkey rsa:2048 -keyout "$E21_CERT/key.pem" -out "$E21_CERT/cert.pem" \
	-days 1 -nodes -subj '/CN=localhost' \
	-addext 'subjectAltName=DNS:localhost,IP:127.0.0.1' >/dev/null 2>&1
mkdir -p "$E21_WORK/data" "$E21_WORK/keys"

E21_USER='sftp-user'
E21_PASS='sftp-pass'

e21_cleanup() {
	if [ -n "${E21_PID:-}" ] && kill -0 "$E21_PID" 2>/dev/null; then
		kill -TERM "$E21_PID" 2>/dev/null
		for _ in 1 2 3 4 5 6 7 8 9 10; do
			kill -0 "$E21_PID" 2>/dev/null || break
			sleep 0.5
		done
		kill -9 "$E21_PID" 2>/dev/null
	fi
	rm -rf "$E21_ROOT" "$E21_WORK" "$E21_CERT"
}
trap e21_cleanup EXIT

# In-case keypair for SFTP key auth.
ssh-keygen -t ed25519 -N '' -f "$E21_WORK/keys/id_ed25519" -C 'e2e21' >/dev/null 2>&1
E21_PUBLINE=$(cat "$E21_WORK/keys/id_ed25519.pub")

# --- launch the private server: s3 + sftp (host key into the workdir) -------
cat > "$E21_WORK/config.json" <<EOF
{
  "dataDir": "$E21_WORK/data",
  "listenAddr": "127.0.0.1:$E21_PORT",
  "certFile": "$E21_CERT/cert.pem",
  "keyFile": "$E21_CERT/key.pem",
  "frontends": [
    {"type": "s3"},
    {"type": "sftp", "listenAddr": "127.0.0.1:$E21_PORT",
     "options": {"hostKeyFile": "$E21_WORK/host_ed25519"}}
  ],
  "identities": [
    {"name": "sftp-rw", "accessKey": "$E21_USER", "secretKey": "$E21_PASS",
     "grants": {"*": "readwrite"}, "sshPublicKeys": ["$E21_PUBLINE"]}
  ]
}
EOF

ZETAOBJECT_ACCESS_KEY=minioadmin ZETAOBJECT_SECRET_KEY=minioadmin \
	ZETAOBJECT_CONFIG="$E21_WORK/config.json" ./zeta-object-server >"$E21_WORK/server.log" 2>&1 &
E21_PID=$!
ENDPOINT="https://127.0.0.1:$E21_PORT"
BASE_URL="$ENDPOINT"
export E2E_ENDPOINT="$ENDPOINT"
if ! wait_for_port 127.0.0.1 "$E21_PORT" 15; then
	echo '  (sftp server did not start — failing case)'
	E2E_FAIL=$((E2E_FAIL + 1))
	exit 0
fi

# Seed state through the S3 side (cross-frontend consistency proof).
printf 'sftp-e2e-seed-body' | AWS_ACCESS_KEY_ID=minioadmin AWS_SECRET_ACCESS_KEY=minioadmin \
	aws s3api put-object --bucket "$E21_BKT" --key 'seed.txt' \
	--body /dev/stdin --endpoint-url "$ENDPOINT" --no-verify-ssl >/dev/null 2>&1

# sftp CLI options: never trust/keep host keys (test host key), force the
# in-case identity, non-interactive batch mode.
E21_SSHOPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o LogLevel=ERROR"
E21_PAYLOAD="$E21_WORK/payload.txt"
printf 'sftp-e2e-payload-roundtrip-abcdef' > "$E21_PAYLOAD"

# --- part 21a: key-auth round-trip via the sftp CLI ---------------------------
cat > "$E21_WORK/batch" <<EOF
put "$E21_PAYLOAD" /$E21_BKT/e2e21.txt
ls /$E21_BKT
get /$E21_BKT/e2e21.txt "$E21_WORK/roundtrip.txt"
rm /$E21_BKT/e2e21.txt
EOF

E21_OUT=$(sftp $E21_SSHOPTS -i "$E21_WORK/keys/id_ed25519" -P "$E21_PORT" \
	-b "$E21_WORK/batch" "$E21_USER@127.0.0.1" 2>"$E21_WORK/sftp.err")
E21_RC=$?
assert_eq 'sftp batch (put/ls/get/rm) exit code' 0 "$E21_RC"

if [ -f "$E21_WORK/roundtrip.txt" ]; then
	assert_eq 'SFTP round-trip is byte-identical' "$(cat "$E21_PAYLOAD")" "$(cat "$E21_WORK/roundtrip.txt")"
else
	assert_contains 'SFTP get produced the file' 'missing-roundtrip.txt' 'present'
fi
assert_contains 'sftp ls showed the uploaded file' "$E21_OUT" 'e2e21.txt'

# The seeded S3 object reads back over SFTP (S3-vs-SFTP parity).
cat > "$E21_WORK/batch-seed" <<EOF
get /$E21_BKT/seed.txt "$E21_WORK/seed-ftp.txt"
EOF
sftp $E21_SSHOPTS -i "$E21_WORK/keys/id_ed25519" -P "$E21_PORT" \
	-b "$E21_WORK/batch-seed" "$E21_USER@127.0.0.1" >/dev/null 2>&1
if [ -f "$E21_WORK/seed-ftp.txt" ]; then
	assert_eq 'S3-written object reads back via SFTP' 'sftp-e2e-seed-body' "$(cat "$E21_WORK/seed-ftp.txt")"
else
	assert_contains 'S3 object fetched via SFTP' 'missing-seed.txt' 'present'
fi

# --- part 21b: host key generated into the configured path ---------------------
if [ -f "$E21_WORK/host_ed25519" ]; then
	assert_eq 'host key auto-generated at hostKeyFile' present present
else
	assert_eq 'host key auto-generated at hostKeyFile' missing present
fi
assert_contains 'server log names the generated host key' "$(cat "$E21_WORK/server.log")" 'host key'

# --- part 21c: negatives (server stays up) -------------------------------------
# Wrong key: generate a second, unregistered keypair.
ssh-keygen -t ed25519 -N '' -f "$E21_WORK/keys/wrong_ed25519" -C 'e2e21-wrong' >/dev/null 2>&1
cat > "$E21_WORK/batch-wrong" <<EOF
ls /$E21_BKT
EOF
sftp $E21_SSHOPTS -i "$E21_WORK/keys/wrong_ed25519" -P "$E21_PORT" \
	-b "$E21_WORK/batch-wrong" "$E21_USER@127.0.0.1" >/dev/null 2>&1
E21_WRONG_RC=$?
if [ "$E21_WRONG_RC" -ne 0 ]; then
	assert_eq 'unregistered key rejected cleanly' denied denied
else
	assert_eq 'unregistered key rejected cleanly' accepted denied
fi

# Wrong password (key auth disabled for this attempt by forcing password via
# empty identity file + PreferredAuthentications=password).
sftp $E21_SSHOPTS -o BatchMode=no -o PreferredAuthentications=password \
	-o NumberOfPasswordPrompts=0 -P "$E21_PORT" \
	-b "$E21_WORK/batch-wrong" "$E21_USER@127.0.0.1" >/dev/null 2>&1
E21_BADPASS_RC=$?
if [ "$E21_BADPASS_RC" -ne 0 ]; then
	assert_eq 'password auth without credentials rejected' denied denied
else
	assert_eq 'password auth without credentials rejected' accepted denied
fi

# Server still serving after the negatives (key-auth ls succeeds).
E21_STILL=$(sftp $E21_SSHOPTS -i "$E21_WORK/keys/id_ed25519" -P "$E21_PORT" \
	-b "$E21_WORK/batch-wrong" "$E21_USER@127.0.0.1" 2>/dev/null)
assert_contains 'server survives negatives (ls works)' "$E21_STILL" "$E21_BKT"

# --- fail-loud: unknown option key aborts startup -------------------------------
E21_FAILOG="$E21_WORK/fail.log"
cat > "$E21_WORK/config-bad.json" <<EOF
{
  "dataDir": "$E21_WORK/data",
  "listenAddr": "127.0.0.1:$E21_PORT",
  "certFile": "$E21_CERT/cert.pem",
  "keyFile": "$E21_CERT/key.pem",
  "frontends": [
    {"type": "sftp", "listenAddr": "127.0.0.1:$E21_PORT", "options": {"bogus": "1"}}
  ]
}
EOF
launch_expect_fail "$E21_WORK/config-bad.json" "$E21_FAILOG" 10
assert_eq 'unknown sftp option aborts startup' 0 "$FAILSTART_EXIT"
assert_contains 'startup log names the unknown key' "$(cat "$E21_FAILOG")" 'bogus'

e2e_finish
